echo "# npp-zero-alerts" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/rrispol/npp-zero-alerts.git
git push -u origin main
